### ISSUE TITLE
create note with empty title

### ISSUE THREAD

**Issue by fi0** [drgrib/alfred-bear#11]
how do I use bnew without arguments? I tried to change it to argument optional but it didnt work.

**Comment by drgrib** [comment]
Making `bnew` create blank notes with no title is not something I would want to enable because it would be too easy to do accidentally and negatively affect the usability of the primary use case. I have almost done this accidentally many times myself and was thankful the feature didn't exist. It also happens annoyingly often to me in the primary Bear application and I have to go back and delete blank notes.

**Comment by drgrib** [comment]
I would be willing to add an explicit `bblank` or `bempty` keyword so the two functions aren't confused.

**Comment by drgrib** [comment]
Actually this isn't possible in the Bear x callback url Scheme:
https://bear.app/faq/X-callback-url%20Scheme%20documentation/

Under `/create`, it states
> Empty notes are not allowed.

So this is an issue to open with the Bear developers and ask them to change their x callback url to add this use case. Then you could re-open here.

**Comment by fi0** [comment]
Thank you for the hints!
