### ISSUE TITLE
Alfred3 = incompatible?

### ISSUE THREAD

**Issue by webwesen** [drgrib/alfred-bear#2]
I run Alfred 3.8.3
- downloaded your app
- installed
- see "Workflow incompatible, please install the latest version of Alfred"

... assumption : Alfred4 only?

**Comment by drgrib** [comment]
Ah. I'm sorry to hear that. It must be. I exported the workflow file using Alfred 4, so it must not be compatible :(

Unfortunately, I don't have the personal bandwidth to download Alfred 3 and debug its functionality. I'll probably only have time to fix bugs that appear on my personal installation for this project.

However, if you are feeling adventurous, you could clone the current master branch to your Alfred installation, build it from the Go source, and export the `.workflow`. I would be happy to add it to the 1.0 release binaries.

**Comment by webwesen** [comment]
i have since installed/purchased Alfred4 Powerpack, so i am all set.
thanks!

**Comment by drgrib** [comment]
Glad to hear it :)

**Comment by preslavrachev** [comment]
@drgrib I am going to build myself a version for Alfred 3. How exactly do I do that? I did not see a `Makefile`, but you seem to be using some VSCode build setup am I right? Do I simply `go build` the three commands and then wire them up in an Alfred workflow?

**Comment by drgrib** [comment]
There are three main paths that come to mind.

## Option 1 - Rewire it yourself
You could do what you are saying, basically using all the same files except the `info.plist`, which you would delete and recreate yourself by wiring it all together and, yes, using `go build` the same way I have in [`.vscode/tasks.json`](https://github.com/drgrib/alfred-bear/blob/master/.vscode/tasks.json).

You would also need to recreate the script filter scripts used in the current `info.plist`, which are simple but may take some time to figure out exactly how to place. The the `bash` code for these script filters is embedded in the current `info.plist` but it may not be intuitive to figure out how they are all connected together in that file because it is in text rather than in the visual workflow editor in Alfred, which is how I edit the file myself and how I originally designed it.

## Option 2 - Make `alfred-bear` compatible with Alfred 3
Another option, which may take the same amount of effort and would help the community, is converting the current `info.plist` to be compatible with Alfred 3.

The guy who wrote [the other Bear workflow](https://github.com/chrisbro/alfred-bear) somehow did that in [this commit](https://github.com/chrisbro/alfred-bear/commit/c9e0a0ddf52b8f38810d7238dd921c33246f102f), which he references briefly in [this issue](https://github.com/chrisbro/alfred-bear/issues/25). I honestly can't figure out what the hell he was doing there and don't have time to but maybe you could and it seems like it may be simpler than the first option. You could then submit a PR with changes to the `info.plist` to this repo, be the hero of other Alfred 3 users of the workflow, and have my gratitude :)

## Option 3 - Use the other Bear workflow directly
Since he already made his version compatible with Alfred 3, you could just use his. The disadvantage of this option is that his version is slower and has fewer features, which is why I created mine.

**Comment by preslavrachev** [comment]
@drgrib The reason I like your workflow is precisely because it is written in Go. I had a chance to test it on my other machine running Alfred 4, and it is ultra fast.

Let me see what I can do, in order to back-port it to Alfred 3. I will let you know.

**Comment by drgrib** [comment]
I'm happy to hear that you see that kind of performance difference. So, given that motivation, I took another look at what he did in his commit, and it looks like it was as simple as just using the visual workflow connection editor in Alfred 3 to create and export the `info.plist` instead of the one in Alfred 4. Which makes total sense because of course they would want Alfred 4 to be compatible with Alfred 3 workflows. And since I'm not using any Alfred 4 specific features for this workflow, it should work fine for all users.

This is a change that would probably be significantly easier for me to do than you, so I'll take the lead on this and look into it this weekend. If you are feeling particularly adventurous or eager to have it working, you are welcome to beat me to it before then :)

**Comment by drgrib** [comment]
Pleased to report this is fixed in #8.

**Comment by preslavrachev** [comment]
@drgrib Thank you! Works awesome on Alfred 3! 🎉

**Comment by prat0318** [comment]
Seeing the same error with the current latest `1.1.6` with Alfred 3. Let me try installing the one built after #8 patch.

**Comment by drgrib** [comment]
@prat0318 Keeping Alfred 3 compatibility was too much manual labor, as it required me to keep a copy of Alfred 3 and manually update its workflow package and plist then copy it back into my Alfred 4, which is the only version I personally use.

This is the last release that supports Alfred 3:
https://github.com/drgrib/alfred-bear/releases/tag/1.0.5

I'm afraid you'll need to upgrade to Alfred 4 if you want the latest features.
