### ISSUE TITLE
Feature Request: Search in Bear

### ISSUE THREAD

**Issue by neo-anderson** [drgrib/alfred-bear#21]
Can you please add something like the "bst" feature from https://github.com/chrisbro/alfred-bear/ ?
I want to search for a tag and then open bear with all the notes having that tag.

Thanks for creating this workflow. Very fast and useful

**Comment by drgrib** [comment]
And you know you can already type `#`, select a tag, and then browse all the notes filtered by that tag right? But you still want to browse within the Bear interface? I've received this request before (#18) and don't really understand it because I think the workflow already supports that functionality.

Glad you are enjoying the workflow.

**Comment by neo-anderson** [comment]
Yes, and it's perfect. But, sometimes I want to see image thumbnails, pinned notes, perform batch actions on multiple notes like copy links or export, etc. I can use the other workflow in addition to this one as well, but I feel adding this feature to your workflow would be "cleaner".

Also, off topic, why is the size of your workflow 25 MBs?

**Comment by drgrib** [comment]
Okay. I'll look into it. Thanks for explaining what the command would be used for. I'll probably use `bt` so as not to conflict with `bs`.

As for the 25 MB workflow size, it's the double-edged sword of using Go executables. Each executable is a completely self-contained instance of the Go runtime. It makes them extremely portable and extremely fast but also quite large. Since I have 5 of them in the workflow for various tasks, each at about 5 MB, that's about 25 MB just from the executables.

**Comment by neo-anderson** [comment]
Got it. Thanks for responding 👍

**Comment by anzax** [comment]
First of all, Thanks @drgrib for your work, I really like what you've done here.
I'm adding +1 to this request, I would like to be able initiate special searches from Alfred prompt. eg.: @today, @images

**Comment by drgrib** [comment]
Thanks @anzax.

Interesting point about `@today` and `@images`. I didn't know those search options existed. With those in mind, I think both those and the tag search feature could be implemented by simply making the `option` key modifier "Search for `{query}` in Bear Main Window" when running `bcs` and `bs`.

I've tested it with tags and it opens to the intended unfolded tag point that I was originally planning to implement with a `bt` keyword. Better to not implement a new keyword module if it is unnecessary from a code perspective and is actually more steps from a user perspective.

**Comment by anzax** [comment]
It could be even better to have auto suggestions/complete for special searches listed here: [Advanced search options in Bear](https://bear.app/faq/Advanced%20search%20options%20in%20Bear).  All of them start from `@`. 
Anyway, just to have an option to open search result in the app would be great.

**Comment by drgrib** [comment]
I had considered that as well. I think that is possible.

**Comment by neo-anderson** [comment]
Hyped for this! :)

**Comment by drgrib** [comment]
Took some time but all these features have been added in #23 👍

Documented here:
https://github.com/drgrib/alfred-bear#search-in-bear-app

**Comment by neo-anderson** [comment]
Worked perfectly. Very intuitive. Thank you so much.
