### ISSUE TITLE
Feature request: Porting "search for a tag"

### ISSUE THREAD

**Issue by Raphomet** [drgrib/alfred-bear#29]
Hello! I love this Workflow—it's a gamechanger for me and I use it several times a day.

I noticed that the original package maintained by chrisbro has a `bst` command that searches tags and opens the appropriate tag in bear. Just wanted to ask you if porting this functionality over is on your development roadmap.

Thanks again.

**Comment by drgrib** [comment]
Hey there! Glad you are enjoying the workflow. It's game changer for me too, funny as that may sound since I wrote most of the code 😄 It makes sense if you see what happened, though, because I added many of these features as requests from users like yourself.

Someone already beat you to this one, though. I implemented it in #21.

Documented here:
https://github.com/drgrib/alfred-bear#search-in-bear-app
