### ISSUE TITLE
Insert wiki-links instead of linking to id

### ISSUE THREAD

**Issue by msageryd** [drgrib/alfred-bear#66]
Bear version 2 now has backlinks, which is great.

Unfortunately, the backlink panel won't generate backlinks based on id-links. Bear support said that they have no plans to implement support for building backlinks from "hard links". They suggested I'd try to get the workflow author to change the links to wiki links.

This is how a "drgib" link looks like after inserting via shift-enter:
<img width="334" alt="image" src="https://github.com/drgrib/alfred-bear/assets/4483085/6e653ee1-66ad-480e-afa9-c0618576e5d9">

This is how a wiki link looks like after draging one note into another.
<img width="377" alt="image" src="https://github.com/drgrib/alfred-bear/assets/4483085/d167ce1c-1623-45a2-8c7d-85ff71b00e32">

I would love to have access to the backlink list, but I cannot work without the superb drgrib-workflow.

**Comment by drgrib** [comment]
Is there a way for you to create a wiki-link purely with markdown without using mouse gestures? I'm afraid mouse gestures are beyond the scope of the workflow.

**Comment by drgrib** [comment]
I see that you can use `[[<note title>]]` but I'm not seeing a way to add the `&new_window=yes` parameter, which would be an unacceptable alteration to the default behavior for my personal workflow since I very rarely use the main window.

I could consider it for a new modifier key other than `<shift>` if there is enough interest for this. Probably displacing `<shift-cmd>` for table of contents and changing table of contents to `<option-cmd>`.

**Comment by msageryd** [comment]
I'm not sure what you mean. The links you create are shown in my first screen shot. I don't see any `new_window` parameter in this link.

If I create a link manually, by typing `[[title of another note]]`, I can then cmd-click on this link to open the linked note in a separate window.

**Comment by drgrib** [comment]
Here is a link that I will paste directly from the workflow by holding shift when selecting it and pressing enter:
![capture](https://github.com/drgrib/alfred-bear/assets/3879367/25e93d5b-8549-4384-b37e-68c76f01321d)

`[cron / crontab](bear://x-callback-url/open-note?id=7DC7E782-AE71-47BE-BD89-6ABFA0B8C7A6-14789-00000CA27EBD6C4C&show_window=yes&new_window=yes)`
Notice the `&new_window=yes`.

Are you saying it isn't functioning like this for you? On reflection, I'm a little confused what the problem is unless you just don't like how the shift-cmd links look.

**Comment by drgrib** [comment]
I see. I was misunderstanding what you meant by backlinks (may have been helpful to explain this in your original post):
https://beta.bear.app/t/bear-2-beta-happy-holidays-update-10084-aka-backlinks/6606

That is a pretty useful feature but it does really suck that you have to cmd-click links to open them in a new window. I'll have to think about whether this is worth overwriting the base shift link or have it displace the current shift-cmd for ToC paste. Either way, I will implement it though since it is a core feature.

**Comment by msageryd** [comment]
I'm sorry for not being more clear.

Fwiw, backlinks are out of beta as of Bear V2 a couple of months ago:
https://bear.app/faq/how-to-use-the-info-panel-table-of-contents-and-backlinks-in-bear/

I also like to open links in new windows. IMO this should not be hard coded into the link, but a setting in Bear. I'll file a feature request with Bear and see how it goes.

**Comment by msageryd** [comment]
Bear support said they will consider this setting, "open links in new window", for future releaes. This would be the best solution IMO.

**Comment by drgrib** [comment]
Completely agree. Thanks for making the feature request.

**Comment by drgrib** [comment]
Implemented in #67. Looking forward to Bear adding that global setting.
